package com.ceva.bank.utils;

public enum TransactionCodes {
	FTINTERBANK, FTINTRABANK, BILLPAYMENT, FTTXNSTATUSQUERY, BALENQ, QRYACT, OPENACT, 
	STMT, NAMEENQ, DEPWALLET, VALIDATEPHONE, CWDBYACT, CWDBYOTP, CASHDEP, REGOTP, ACTOTP, 
	MMO, AIRTIME, CWDBYCARD, CWDOTRBNK;
}
