package com.ceva.bank.utils;

public enum TransactionCodes {
CASHDEP,FTINTERBANK,FTINTRABANK,BILLPAYMENT,FTTXNSTATUSQUERY,BALENQ,QRYACT,
OPENACT,STMT,NAMEENQ,DEPWALLET,VALIDATEPHONE,CWDBYACT,CWDBYOTP,RMBYACT,MMO,AIRTIME;
}