package com.ceva.bank.utils;

public enum TransactionCodes {
	FTINTERBANK, FTINTRABANK, BILLPAYMENT, FTTXNSTATUSQUERY, BALENQ, QRYACT, OPENACT, 
	STMT, NAMEENQ, DEPWALLET,FMDEPOSIT,FMWITHDRAW, VALIDATEPHONE, CWDBYACT, CWDBYOTP, CASHDEP, REGOTP, ACTOTP, 
	MMO, AIRTIME, CWDBYCARD, CWDOTRBNK, USSDWITHDRAW,BVNOPENACT;
}
